# Generated by Django 3.2.5 on 2021-08-23 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App', '0002_auto_20210818_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fashion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('write_by', models.CharField(max_length=100)),
                ('discription', models.TextField()),
                ('step1', models.TextField()),
                ('step2', models.TextField()),
                ('step3', models.TextField()),
                ('step4', models.TextField()),
                ('step5', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('view_count', models.IntegerField(default=0)),
                ('author', models.CharField(max_length=100)),
                ('author_img', models.ImageField(upload_to='images/author')),
                ('thumbnail', models.ImageField(upload_to='images/thumbnail/')),
                ('featured', models.BooleanField()),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.category')),
            ],
        ),
    ]
